version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: sisdb_examen
      MYSQL_USER: root123
      MYSQL_PASSWORD: abcd
    ports:
      - "3307:3306"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
